#pragma once

enum SecondaryEffect {NOEFFECT,NORMAL_POISON,PARALYZE,SLEEP,BURN,FREEZE,BAD_POISON,ATTACK_CHANGE,DEFENSE_CHANGE,SP_ATTACK_CHANGE,SP_DEFENSE_CHANGE,SPEED_CHANGE,FLINCH,CONFUSE,TRI_ATTACK};