server {
    listen 443;
    server_name npcshowdown.com;

    root /npcs/static;
    index index.html;

    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # It's an SPA, so need to serve index.html for all other routes
    location / {
        try_files $uri /index.html;
    }
}
