#pragma once

class Ability;
class Battle;
enum DamageCategory;
class Effect;
struct EffectState;
enum Event;
class EventArgs;
class FieldEffect;
enum Gender;
class Item;
class Move;
class MoveUse;
enum Nature;
class Observer;
class Pokemon;
class PokemonBlueprint;
enum SecondaryEffect;
enum Stat;
class Status;
enum TargetType;
class Trainer;
enum Type;
class Weather;