name: Build, package, and upload the application

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Setting up SSH keys for private repos
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.TFLIB_SSH_KEY }}
          ${{ secrets.TFHTTP_SSH_KEY }}



    - name: Init submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt install npm
      
    - name: Build Backend and Run Tests
      run: |
        cd backend
        cmake --preset debug
        cd out/debug
        cmake --build .
        ./npcs_tests
        ./npcshowdown -t
        
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm install -g @angular/cli
        ng build