name: Build and Release app

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Setting up SSH keys for private repos
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.TFLIB_SSH_KEY }}
          ${{ secrets.TFHTTP_SSH_KEY }}

    - name: Init submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt install npm
      
    - name: Build Backend and Run Tests
      run: |
        cd backend
        cmake --preset release
        cd out/release
        cmake --build .
        ./npcs_tests
        
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm install -g @angular/cli
        ng build

    - name: Package App
      run: |
        mkdir -p package
        cp ./backend/out/release/npcshowdown package/
        cp -r ./frontend/dist/npcshowdown package/static
        cd package
        tar -czvf ../npcs-ubuntu-x64-v0.0.${{ github.run_number }}.tar.gz ./static ./npcshowdown
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{ github.run_number }}
        release_name: Release v0.0.${{ github.run_number }}
        prerelease: true

    - name: Publish release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./npcs-ubuntu-x64-v0.0.${{ github.run_number }}.tar.gz
        asset_name: npcs-ubuntu-x64-v0.0.${{ github.run_number }}.tar.gz
        asset_content_type: application/octet-stream
