name: CD

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
        VERSION: 0.1.3
    steps:
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PROD_SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER_IP }} "echo Connected"

    - name: Check out repo
      uses: actions/checkout@v4

    - name: Setting up SSH keys for private repos
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.TFLIB_SSH_KEY }}
          ${{ secrets.TFHTTP_SSH_KEY }}



    - name: Init submodules
      run: git submodule update --init --recursive
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt install npm
      
    - name: Build Backend and Run Tests
      run: |
        cd backend
        cmake --preset release
        cd out/release
        cmake --build .
        ./npcs_tests
        
    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm install -g @angular/cli
        ng build

    - name: Package App
      run: |
        mkdir -p package
        cp ./backend/out/release/npcshowdown package/
        cp -r ./frontend/dist/npcshowdown package/static
        cp deploy/* package/
        cd package
        tar -czvf ../npcs-ubuntu-x64-v${{ env.VERSION }}.tar.gz ./static ./npcshowdown ./create-tables-prod.sql ./install_ubuntu.sh ./npcshowdown.conf ./npcshowdown.service ./deploy.sh
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.VERSION }}
        release_name: Release v${{ env.VERSION }}
        prerelease: true

    - name: Publish release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./npcs-ubuntu-x64-v${{ env.VERSION }}.tar.gz
        asset_name: npcs-ubuntu-x64-v${{ env.VERSION }}.tar.gz
        asset_content_type: application/octet-stream

    - name: Deploy App
      run: |
        scp npcs-ubuntu-x64-v${{ env.VERSION }}.tar.gz ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER_IP }}:~/npcs-new.tar.gz
        ssh ${{ secrets.PROD_USER }}@${{ secrets.PROD_SERVER_IP }} '~/deploy.sh'